DAC6-2288 :  click browser back button
hmrc/disclose-cross-border-arrangements-frontend pull request #184
Opened 2023-02-13 15:40 UTC by AashuChauhanHmrc

2023-02-14 10:11 UTC, BriWak requested changes

2023-02-14 10:11 UTC, BriWak commented on conf/messages.en
> +informationSent.heading = Information Sent
this should be a lowercase s for Information sent, otherwise LGTM

2023-02-15 09:11 UTC, BriWak submitted a review, later dismissed

2023-02-23 17:36 UTC, ers2015112 approved these changes

2023-02-24 10:13 UTC, merged